// <auto-generated />
using CardAPI.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace CardAPI.Migrations
{
    [DbContext(typeof(CardContext))]
    partial class CardContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("CardAPI.Model.CardContext+Card", b =>
                {
                    b.Property<int>("CardID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CardName");

                    b.Property<int>("CardNumber");

                    b.Property<int>("CardType");

                    b.HasKey("CardID");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("CardAPI.Model.CardContext+CardOption", b =>
                {
                    b.Property<int>("CardOptionID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Action");

                    b.Property<int?>("CardID");

                    b.Property<string>("Result");

                    b.HasKey("CardOptionID");

                    b.HasIndex("CardID");

                    b.ToTable("CardOptions");
                });

            modelBuilder.Entity("CardAPI.Model.CardContext+Stage", b =>
                {
                    b.Property<int>("CardID");

                    b.Property<int>("CardOptionID");

                    b.HasKey("CardID", "CardOptionID");

                    b.HasIndex("CardOptionID");

                    b.ToTable("Stage");
                });

            modelBuilder.Entity("CardAPI.Model.CardContext+CardOption", b =>
                {
                    b.HasOne("CardAPI.Model.CardContext+Card", "Card")
                        .WithMany("Options")
                        .HasForeignKey("CardID");
                });

            modelBuilder.Entity("CardAPI.Model.CardContext+Stage", b =>
                {
                    b.HasOne("CardAPI.Model.CardContext+Card", "toBeStaged")
                        .WithMany("StagedBy")
                        .HasForeignKey("CardID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CardAPI.Model.CardContext+CardOption", "StagedBy")
                        .WithMany("Stages")
                        .HasForeignKey("CardOptionID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
